#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"

# Force look in /usr/bin if local file not found
if [ -f ./$module.ko ]; then
    insmod ./$module.ko $* || exit 1
else
    # This is where Buildroot puts it
    insmod /usr/bin/$module.ko $* || exit 1
fi

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

rm -f /dev/${device}
mknod /dev/${device} c $major 0
chmod $mode /dev/${device}
